version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine3.17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5455:5432"
    environment:
      - POSTGRES_USER=my_proj
      - POSTGRES_PASSWORD=my_proj
      - POSTGRES_DB=my_proj_dev

volumes:
  postgres_data:
  app: